name: weather
description: "Weather app for user location"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1
  go_router: ^13.2.2
  internet_connection_checker: ^3.0.1
  dartz: ^0.10.1
  dio: ^5.7.0
  geolocator: ^13.0.2
  permission_handler: ^11.2.1
  get_it: ^8.0.3
  envied: ^1.1.1
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mocktail: ^1.0.3
  logger: ^2.5.0
  # HTTP Inspector tool for Flutter which helps debugging http requests.
  requests_inspector: ^4.2.1
  build_runner: ^2.5.4
  envied_generator: ^1.1.1

flutter:
  uses-material-design: true
